AllCops:
  Include:
    - 'lib/**/*.rb'
  Exclude:
     - '.bundle/**/*'
     - 'Gemfile'
     - 'bin/**/*'
     - 'coverage/**/*'
     - 'spec/**/*'
     - 'target/**/*'
     - 'test/**/*'
     - 'tmp/**/*'
